name: Create Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  get_libs:

    runs-on: ubuntu-latest

    steps:
    - name: Check out image-io-libs from my repo
      uses: actions/checkout@master
      with:
        repository: sygslhy/image-io-libs
